### PR TITLE
feat(plugin-bundle-node): Use `mainFields` option for `rollup-plugin-node-resolve`.

### PR DESCRIPTION
**Pull request by umidbekkarimov**
Related to #37

### CODE REVIEW

**Comment by FredKSchott** [comment]
Nice! I need to fix this in @pika/web as well

**Comment by tunnckoCore** [comment]
Why? I only see this as a minus. Why not bundle `module` field too when possible, we can save some size on the final CJS.

And yes, I know we have `*-bundle-web` plugin.

**Comment by FredKSchott** [comment]
The old syntax was deprecated, which is why we moved to `mainFields`.
In general, the "module" entrypoint is more likely to be the "web" version of the two. That is my fear in turning "module" on for node-builders.

**Comment by tunnckoCore** [comment]
I know. The question was more meant to be for this diff

```diff
- module: false,
+ mainFields: ['main'],
```


The thing is why not leave the rollup's defaults `[module, main]`, but force only to resolve from the `main`.

No matter that we bundle for nodejs we still can save some bytes when its dependencies have a `module` field. Believe me, I'm in the business with Rollup for a long time :dancer: It's because the tree-shaking still will apply on those of package 's dependencies which have `module` field.

> That is my fear in turning "module" on for node-builders.

I don't understand exactly. Why are you fearing? They still will build only CJS anyway.

**Pull request merged**
