### PR TITLE
feat: add plugin-bundle-types

### PR DESCRIPTION
**Pull request by layershifter**
This PR adds a new plugin to generate a bundle of TS definitions, it makes a big sense for `web` and `node` builds.

### CODE REVIEW

**Comment by FredKSchott** [comment]
This is great! I was actually looking for something like this a while ago, but couldn't get it to work. How stable is `dts-bundle-generator`? Does it run successfully 100% of the time? Is there anything that can go in a type definition file that it can't handle?

**Comment by layershifter** [comment]
https://www.npmjs.com/package/dts-bundle-generator#known-limitations
They have an own list of limitations, for small packages that I have tried with this plugin works like a charm.

https://github.com/Swatinem/rollup-plugin-dts/issues/5 - this issue contains some compassion on issues

**Comment by FredKSchott** [comment]
Ah, yes that's right. I ran into similar problems when I tried this originally.

This is something that I very much want, but right now I'd be against publishing an official bundler with so many caveats. I would definitely point to it as a community plugin (currently working on a page on pikapkg.com to highlight these better).

**Comment by layershifter** [comment]
Okay, I understand your concern there 👍
I will publish it as own package.

**Comment by FredKSchott** [comment]
Great, thanks for understanding. 

And please do publish it yourself! And once you do, link it here so that we can add it to the README (or feel free to create that PR yourself)

**Pull request closed without merging**
